In [ ]:
#importar a base de dados:
import pandas as pd

tabela = pd.read_csv("cancelamentos.csv")

#remover o CostumerID por ser irrelevante:
tabela = tabela.drop(columns="CustomerID")
display(tabela)

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [4]:
#mostra as informações da tabela:
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   50000 non-null  float64
 1   sexo                    49997 non-null  str
 2   tempo_como_cliente      49998 non-null  float64
 3   frequencia_uso          50000 non-null  float64
 4   ligacoes_callcenter     50000 non-null  float64
 5   dias_atraso             50000 non-null  float64
 6   assinatura              50000 non-null  str
 7   duracao_contrato        50000 non-null  str
 8   total_gasto             50000 non-null  float64
 9   meses_ultima_interacao  50000 non-null  float64
 10  cancelou                50000 non-null  float64
dtypes: float64(8), str(3)
memory usage: 4.2 MB

None

In [5]:
#remover as informações vazias:
tabela = tabela.dropna()
display(tabela.info())

<class 'pandas.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  str
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  str
 7   duracao_contrato        49996 non-null  str
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), str(3)
memory usage: 4.6 MB

None

In [6]:
#mostra pessoas que cancelaram e não cancelaram em quantidade:
display(tabela["cancelou"].value_counts())

#mostra pessoas que cancelaram e não cancelaram em porcentagem:
#normalize=True faz mostrar em porcentagem, e o .map("{:.1%}".format) faz mostrar somente uma casa decimal depois da vírgula
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

cancelou
1.0    28393
0.0    21603
Name: count, dtype: int64

cancelou
1.0    56.8%
0.0    43.2%
Name: proportion, dtype: str

In [7]:
#mostra em porcentagem as pessoas que estão em cada tipo de contrato:
display(tabela["duracao_contrato"].value_counts(normalize=True).map("{:.1%}".format))
display(tabela["duracao_contrato"].value_counts())

duracao_contrato
Annual       40.3%
Quarterly    39.9%
Monthly      19.8%
Name: proportion, dtype: str

duracao_contrato
Annual       20156
Quarterly    19956
Monthly       9884
Name: count, dtype: int64

In [8]:
#agrupa as informações da coluna e faz uma média das informações de colunas da tabela:
display(tabela.groupby("duracao_contrato").mean(numeric_only=True))

,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
duracao_contrato,,,,,,,,
Annual,38.783985,31.416452,15.910449,3.277585,12.533985,650.925840,14.231544,0.464080
Monthly,41.428470,30.677964,15.577600,4.923917,15.078814,547.508921,15.392655,1.000000
Quarterly,38.833935,31.522099,15.842504,3.256113,12.480006,654.102443,14.364602,0.458759

- TODOS QUE SÃO DO CONTRATO MENSAL CANCELARAM O SERVIÇO!!

In [9]:
#removeremos o contrato Monthly	para saber o impacto que ele vai fazer na coluna de cancelou:
tabela = tabela[tabela["duracao_contrato"] != "Monthly"]
display(tabela)
#agora não temos o valor Monthly na coluna de duracao_contrato

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
6,49.0,Male,6.0,7.0,0.0,0.0,Standard,Annual,751.00,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
49994,63.0,Male,16.0,24.0,2.0,18.0,Standard,Quarterly,442.00,26.0,1.0
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [10]:
display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))
#observamos o impacto que remover o Monthly fez na coluna Cancelou:

cancelou
0.0    21603
1.0    18509
Name: count, dtype: int64

cancelou
0.0    53.9%
1.0    46.1%
Name: proportion, dtype: str

- DE 56% CAIU PRA 46%

In [11]:
#agora vamos observar como a assinatura está distribuída na tabela em porcentagem:
display(tabela["assinatura"].value_counts(normalize=True).map("{:.1%}".format))
#e a sua média em comparação é:
display(tabela.groupby("assinatura").mean(numeric_only=True))

assinatura
Standard    34.3%
Premium     33.3%
Basic       32.3%
Name: proportion, dtype: str

,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
assinatura,,,,,,,,
Basic,38.777049,32.266908,15.938459,3.328064,12.538752,648.339261,14.317036,0.476517
Premium,38.885766,31.120813,15.762111,3.238038,12.430697,653.459842,14.306071,0.453947
Standard,38.764035,31.055850,15.929697,3.237345,12.551601,655.504070,14.271479,0.454499

- AS PROPORÇÕES SÃO QUASE AS MESMAS, NÃO DEVEMOS JULGA LAS PELA ASSINATURA.

In [12]:
#criaremos um gráfico para melhor visualização:
import plotly.express as px

for coluna in tabela: #o padrão itera sobre colunas da base de dados
    grafico = px.histogram(tabela, x=coluna, color="cancelou", width=600)
    grafico.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

- DEPOIS DE 20 DIAS DE ATRASO O CLIENTE CANCELA.
- DEPOIS DE 5 LIGAÇÕES O CLIENTE CANCELA.
- PESSOAS ACIMA DE 50 ANOS CANCELAM.

In [13]:
#iremos remover essas informações para observar a diferença:
tabela = tabela[tabela["ligacoes_callcenter"]<5]#ira contar apenas os clientes com ligações menores que 5...
tabela = tabela[tabela["dias_atraso"]<=20]
tabela = tabela[tabela["idade"]<50]
display(tabela)
display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
6,49.0,Male,6.0,7.0,0.0,0.0,Standard,Annual,751.00,11.0,0.0
7,33.0,Male,15.0,18.0,1.0,20.0,Standard,Annual,839.71,25.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
49984,40.0,Female,57.0,22.0,0.0,0.0,Premium,Annual,711.97,4.0,0.0
49988,34.0,Female,43.0,1.0,3.0,19.0,Premium,Annual,754.02,11.0,0.0
49991,24.0,Female,33.0,28.0,1.0,11.0,Premium,Annual,844.05,9.0,0.0
49992,37.0,Male,46.0,29.0,2.0,9.0,Standard,Quarterly,517.86,3.0,0.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0

cancelou
0.0    20602
1.0     2892
Name: count, dtype: int64

cancelou
0.0    87.7%
1.0    12.3%
Name: proportion, dtype: str

- DE 46% CAIU PARA 12.3%